spring:
  application:
    name: maplewood

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${DB_URL:jdbc:sqlite:maplewood_school.sqlite}

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
